### ISSUE TITLE
Add Nuget API key to appveyor.yml

### ISSUE THREAD

**Issue by devesh-shetty** [snowplow/snowplow-dotnet-analytics-sdk#4]
Based on discussion with @ninjabear, he suggested using appveyor instead of travis for CI/CD because travis support is not that good for .NET as compared to appveyor.
 
@alexanderdean, please add the encrypted Nuget API Key (NUGET_API_KEY) in appveyor.yml

**Comment by alexanderdean** [comment]
Re-assigning to @ninjabear to handle
